language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=activity_feed --omit=*/settings.py,*/tests/*.py,*/migrations/*.py manage.py test

after_success:
  coveralls
